# Generated by Django 5.0.8 on 2024-08-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name_en'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name_en'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RemoveField(
            model_name='district',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(default='', max_length=150, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_oz',
            field=models.CharField(default='', max_length=150, verbose_name='Uzbek kyril'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(default='', max_length=150, verbose_name='Russian'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(default='', max_length=150, verbose_name='Uzbek latin'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(default='', max_length=150, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_oz',
            field=models.CharField(default='', max_length=150, verbose_name='Uzbek kyril'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(default='', max_length=150, verbose_name='Russian'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(default='', max_length=150, verbose_name='Uzbek latin'),
        ),
    ]
