# Generated by Django 5.0.6 on 2024-07-28 21:55

import apps.users.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_full_name_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('login', 'Login')], default='login', max_length=20)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[apps.users.validator.validate_uzbekistan_phone], verbose_name='Phone Number')),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
