# Generated by Django 5.0.8 on 2024-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_pasport_serial_number_user_passport_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('oz', 'Uzbek kyril')], default='uz', max_length=2),
        ),
    ]
