# Generated by Django 5.0.8 on 2024-09-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='offer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
