# Generated by Django 5.0.6 on 2024-08-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notif_type', models.CharField(choices=[('new_msg', 'New Message'), ('offer_accept', 'Offer Accepted'), ('offer_reject', 'Offer Rejected'), ('info', 'Info')], default='info', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
