# Generated by Django 5.0.6 on 2024-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
