# Generated by Django 5.0.8 on 2024-08-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=150, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_oz',
            field=models.CharField(default='', max_length=150, verbose_name='Uzbek kyril'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=150, verbose_name='Russian'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default='', max_length=150, verbose_name='Uzbek latin'),
        ),
    ]
