# Generated by Django 5.0.8 on 2024-08-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_offer_ad_alter_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='owner_was_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='worker_was_completed',
            field=models.BooleanField(default=False),
        ),
    ]
