# Generated by Django 5.0.8 on 2024-09-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_offer_owner_was_confirmed_offer_worker_was_completed'),
        ('chat', '0003_alter_chat_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.ad'),
        ),
    ]
